@baseUrl = http://localhost:4000/api

### =========================
### Login Admin
### =========================
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "ismael@email.com",
  "password": "hash_de_prueba"
}

###

### Capturar tokens automáticamente
@accessToken = {{login.response.body.access_token}}
@refreshToken = {{login.response.body.refresh_token}}

### =========================
### Obtener usuario actual
### =========================
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

### =========================
### Refresh token
### =========================
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

### =========================
### Logout
### =========================
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

### =========================
### Crear invitación
### (admin/supervisor)
### =========================
# @name invitations
POST {{baseUrl}}/invitations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "role_id": 3,
  "email": "Denilson@correo.com"
}

### Capturar tokens automáticamente
@tokenLink = {{invitations.response.body.token}}
### =========================
### Validar invitación
### =========================
GET {{baseUrl}}/invitations/validate?token={{tokenLink}}

### =========================
### Registrar usuario con invitación
### =========================
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "name": "Denilson",
  "password": "123456",
  "token": "{{tokenLink}}"
}

### =========================
### Obtener roles
### =========================
GET {{baseUrl}}/roles
Authorization: Bearer {{accessToken}}

### =========================
### Obtener usuarios
### =========================
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}


###
GET {{baseUrl}}/projects?scope=mine
Authorization: Bearer {{accessToken}}


### =========================================================================
### MÓDULO DE PROYECTOS
### =========================================================================

### 1. Crear un proyecto nuevo
# @name createProject
POST {{baseUrl}}/projects
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "12",
  "description": "Modelado de estructura residencial de 5 pisos",
  "location": "Puno, Perú",
  "start_date": "2026-08-01",
  "end_date": "2027-02-28"
}

### Capturar el ID del proyecto creado automáticamente
@createdProjectId = {{createProject.response.body.project_id}}


### 2. Listar proyectos (Filtro por defecto o 'mine')
GET {{baseUrl}}/projects?scope=mine
Authorization: Bearer {{accessToken}}


### 3. Listar todos los proyectos disponibles (Owner, member, etc.)
GET {{baseUrl}}/projects?scope=all
Authorization: Bearer {{accessToken}}


### 4. Obtener un proyecto específico por ID
GET {{baseUrl}}/projects/{{createdProjectId}}
Authorization: Bearer {{accessToken}}


### 5. Actualizar proyecto (Caso Exitoso - Modificando campos)
PATCH {{baseUrl}}/projects/{{createdProjectId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Proyecto BIM - Nombre Editado",
  "description": "Nueva descripción actualizada"
}


### 6. Actualizar proyecto (Caso de Error - Cuerpo Vacío)
### 🚨 Esto debería devolver tu error 400 (NO_FIELDS_TO_UPDATE)
PATCH {{baseUrl}}/projects/{{createdProjectId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name" : ""
}


### 7. Eliminar un proyecto por ID
DELETE {{baseUrl}}/projects/{{createdProjectId}}
Authorization: Bearer {{accessToken}}


### =========================================================================
### MÓDULO DE ROLES DE PROYECTO (PROJECT ROLES)
### =========================================================================

### 1. Crear un nuevo rol de proyecto personalizado
# @name createProjectRole
POST {{baseUrl}}/project-roles
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Modelador BIM Senior"
}

### Capturar automáticamente el ID del rol de proyecto creado
@createdProjectRoleId = {{createProjectRole.response.body.project_role_id}}


### 2. Listar roles de proyecto (Por defecto trae combinados: defaults + creados por mí)
GET {{baseUrl}}/project-roles
Authorization: Bearer {{accessToken}}


### 3. Listar roles filtrando por Scope 'default' (Para cuando implementes el Query Schema)
GET {{baseUrl}}/project-roles?scope=default
Authorization: Bearer {{accessToken}}


### 4. Listar roles filtrando por Scope 'owner' (Solo los creados por mí)
GET {{baseUrl}}/project-roles?scope=owner
Authorization: Bearer {{accessToken}}


### 5. Actualizar el nombre de un rol de proyecto (Caso Exitoso)
PATCH {{baseUrl}}/project-roles/{{createdProjectRoleId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Coordinador BIM Líder"
}


### 6. Actualizar rol (Caso de Error - Nombre vacío)
PATCH {{baseUrl}}/project-roles/{{createdProjectRoleId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": ""
}


### 7. Intentar eliminar un rol por defecto o en uso (Caso de Error esperado: 400 o 404)
### 💡 Nota: Puedes probar cambiar el ID por uno que sepas que está asignado a un miembro
DELETE {{baseUrl}}/project-roles/2
Authorization: Bearer {{accessToken}}


### 8. Eliminar el rol de proyecto personalizado creado (Caso Exitoso)
DELETE {{baseUrl}}/project-roles/{{createdProjectRoleId}}
Authorization: Bearer {{accessToken}}